<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'name'              => 'Aaranya Greens',
                'slug'              => 'aaranya-greens',
                'category'          => 'Residential',
                'location'          => 'Gomti Nagar',
                'city'              => 'Lucknow',
                'status'            => 'Ongoing',
                'year'              => 2025,
                'hero_image'        => 'https://images.pexels.com/photos/18506889/pexels-photo-18506889.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/18506889/pexels-photo-18506889.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/18506889/pexels-photo-18506889.jpeg?auto=compress&cs=tinysrgb&w=1200',
                    'https://images.pexels.com/photos/16110999/pexels-photo-16110999.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'A low-rise residential enclave where architecture dissolves into landscape.',
                'long_description'  => 'Aaranya Greens is a collection of garden residences built around the idea that a home should breathe before it impresses. Deep verandas, cross-ventilated rooms, and a central forest court make the project feel less like a building and more like a place that grew.',
                'website_url'       => 'https://example.com/aaranya-greens',
                'rera_number'       => 'UPCPR/2025/001',
                'project_type'      => '2 & 3 BHK Residences',
                'configuration'     => '12 towers · 6 storeys',
                'area'              => '4.2 acres',
                'amenities'         => json_encode(['Forest court', 'Infinity pool', 'Co-working club', 'Walking trails']),
                'featured'          => true,
                'display_order'     => 1,
            ],
            [
                'name'              => 'Meridian One',
                'slug'              => 'meridian-one',
                'category'          => 'Commercial',
                'location'          => 'Sector 62',
                'city'              => 'Delhi NCR',
                'status'            => 'Ongoing',
                'year'              => 2025,
                'hero_image'        => 'https://images.pexels.com/photos/14989324/pexels-photo-14989324.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/14989324/pexels-photo-14989324.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/14989324/pexels-photo-14989324.jpeg?auto=compress&cs=tinysrgb&w=1200',
                    'https://images.pexels.com/photos/12705203/pexels-photo-12705203.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'A vertical workplace designed for the way people actually think and meet.',
                'long_description'  => 'Meridian One reimagines the office tower as a series of connected terraces. Floors step back to create outdoor work rooms in the sky, while a shaded public plinth grounds the building in the street life of the city.',
                'website_url'       => 'https://example.com/meridian-one',
                'rera_number'       => 'HRERA/2024/014',
                'project_type'      => 'Grade-A Offices',
                'configuration'     => '28 floors',
                'area'              => '2.1 million sq. ft.',
                'amenities'         => json_encode(['Sky terraces', 'Conference hub', 'F&B court', 'EV charging']),
                'featured'          => false,
                'display_order'     => 2,
            ],
            [
                'name'              => 'Srishti Township',
                'slug'              => 'srishti-township',
                'category'          => 'Townships',
                'location'          => 'Sultanpur Road',
                'city'              => 'Lucknow',
                'status'            => 'Ongoing',
                'year'              => 2026,
                'hero_image'        => 'https://images.pexels.com/photos/31656168/pexels-photo-31656168.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/31656168/pexels-photo-31656168.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/31656168/pexels-photo-31656168.jpeg?auto=compress&cs=tinysrgb&w=1200',
                    'https://images.pexels.com/photos/6168453/pexels-photo-6168453.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'A 120-acre township built around a restored monsoon lake.',
                'long_description'  => 'Srishti is planned around water. A revived lake sits at its centre, with neighbourhoods fanning outward in walkable clusters — homes, schools, a market street, and a civic square that becomes the heart of a new district.',
                'website_url'       => 'https://example.com/srishti',
                'rera_number'       => 'UPCPR/2024/077',
                'project_type'      => 'Integrated Township',
                'configuration'     => '1,800 homes · 3 schools · 1 market street',
                'area'              => '120 acres',
                'amenities'         => json_encode(['Lake promenade', 'Schools', 'Market street', 'Civic square']),
                'featured'          => true,
                'display_order'     => 3,
            ],
            [
                'name'              => 'Avasa Plots',
                'slug'              => 'avasa-plots',
                'category'          => 'Plotted',
                'location'          => 'Faizabad Road',
                'city'              => 'Lucknow',
                'status'            => 'Upcoming',
                'year'              => 2026,
                'hero_image'        => 'https://images.pexels.com/photos/24419877/pexels-photo-24419877.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/24419877/pexels-photo-24419877.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/24419877/pexels-photo-24419877.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'Villa plots set within an existing mango orchard.',
                'long_description'  => 'Avasa keeps what is already there. The master plan was drawn around a working mango orchard, so roads curve to keep trees and every plot opens onto a green edge rather than a boundary wall.',
                'website_url'       => 'https://example.com/avasa',
                'rera_number'       => 'UPCPR/2026/003',
                'project_type'      => 'Villa Plots',
                'configuration'     => '240 plots · 1,200–3,600 sq. ft.',
                'area'              => '22 acres',
                'amenities'         => json_encode(['Orchard walks', 'Club pavilion', 'Solar grid', 'Jogging loops']),
                'featured'          => false,
                'display_order'     => 4,
            ],
            [
                'name'              => 'Kosh Mixed Quarter',
                'slug'              => 'kosh-mixed-quarter',
                'category'          => 'Mixed-Use',
                'location'          => 'Hazratganj',
                'city'              => 'Lucknow',
                'status'            => 'Ongoing',
                'year'              => 2025,
                'hero_image'        => 'https://images.pexels.com/photos/35142390/pexels-photo-35142390.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/35142390/pexels-photo-35142390.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/35142390/pexels-photo-35142390.jpeg?auto=compress&cs=tinysrgb&w=1200',
                    'https://images.pexels.com/photos/38026454/pexels-photo-38026454.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'A city block that stitches retail, stays and studios into one place.',
                'long_description'  => 'Kosh is a quarter, not a building. A covered lane runs through it, opening into a courtyard where a bookstore, a café, a boutique hotel and a small theatre share the same ground. It is a piece of old city life, rebuilt for now.',
                'website_url'       => 'https://example.com/kosh',
                'rera_number'       => 'UPCPR/2025/052',
                'project_type'      => 'Retail · Hotel · Studios',
                'configuration'     => '1 covered street · 1 courtyard',
                'area'              => '3.4 acres',
                'amenities'         => json_encode(['Boutique hotel', 'Bookstore', 'Theatre', 'Rooftop bar']),
                'featured'          => false,
                'display_order'     => 5,
            ],
            [
                'name'              => 'Vanya Heights',
                'slug'              => 'vanya-heights',
                'category'          => 'Residential',
                'location'          => 'Vibhuti Khand',
                'city'              => 'Lucknow',
                'status'            => 'Completed',
                'year'              => 2024,
                'hero_image'        => 'https://images.pexels.com/photos/16110999/pexels-photo-16110999.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/16110999/pexels-photo-16110999.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/16110999/pexels-photo-16110999.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'A slender residential tower shaped by light and cross-breeze.',
                'long_description'  => 'Vanya Heights is a single tower, deliberately thin, so every home faces two directions. The form comes from climate, not style — deep fins cut the sun, and the narrow plan lets air move through.',
                'website_url'       => 'https://example.com/vanya',
                'rera_number'       => 'UPCPR/2022/088',
                'project_type'      => '3 & 4 BHK Residences',
                'configuration'     => '1 tower · 22 storeys',
                'area'              => '1.1 acres',
                'amenities'         => json_encode(['Sky lounge', 'Pool deck', 'Reading room', 'Guest suites']),
                'featured'          => false,
                'display_order'     => 6,
            ],
            [
                'name'              => 'Terra Square',
                'slug'              => 'terra-square',
                'category'          => 'Commercial',
                'location'          => 'Sector 18',
                'city'              => 'Delhi NCR',
                'status'            => 'Completed',
                'year'              => 2023,
                'hero_image'        => 'https://images.pexels.com/photos/12705203/pexels-photo-12705203.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/12705203/pexels-photo-12705203.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/12705203/pexels-photo-12705203.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'A shaded public square wrapped with retail and a film theatre.',
                'long_description'  => 'Terra Square turns a commercial block inside out. The shops face inward to a shaded court, and a single-screen theatre sits as a quiet object at its centre — a place to meet before and after a film.',
                'website_url'       => 'https://example.com/terra',
                'rera_number'       => 'HRERA/2021/040',
                'project_type'      => 'Retail & Entertainment',
                'configuration'     => '4 levels · 1 cinema',
                'area'              => '5.8 acres',
                'amenities'         => json_encode(['Central court', 'Cinema', 'Food hall', 'Underground parking']),
                'featured'          => false,
                'display_order'     => 7,
            ],
            [
                'name'              => 'Anant Vihar',
                'slug'              => 'anant-vihar',
                'category'          => 'Townships',
                'location'          => 'Mughalsarai',
                'city'              => 'Varanasi',
                'status'            => 'Completed',
                'year'              => 2022,
                'hero_image'        => 'https://images.pexels.com/photos/4424414/pexels-photo-4424414.jpeg?auto=compress&cs=tinysrgb&w=1600',
                'thumbnail'         => 'https://images.pexels.com/photos/4424414/pexels-photo-4424414.jpeg?auto=compress&cs=tinysrgb&w=800',
                'gallery'           => json_encode([
                    'https://images.pexels.com/photos/4424414/pexels-photo-4424414.jpeg?auto=compress&cs=tinysrgb&w=1200',
                ]),
                'short_description' => 'A river-edge township that reuses the old brick kilns of the site.',
                'long_description'  => 'Anant Vihar was built on a disused brick kiln yard. The kilns were kept as landmarks and the new homes were laid out along the old clay paths, so the memory of making stays in the place that was made.',
                'website_url'       => 'https://example.com/anant',
                'rera_number'       => 'UPRERA/2020/011',
                'project_type'      => 'Integrated Township',
                'configuration'     => '640 homes · 1 school',
                'area'              => '48 acres',
                'amenities'         => json_encode(['River walk', 'Kiln park', 'School', 'Community hall']),
                'featured'          => false,
                'display_order'     => 8,
            ],
        ];

        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}
